on: 
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  issues:
    types: [opened]


jobs:
  comment_job:
    runs-on: ubuntu-latest
    name: Label Pull requests
    steps:
      # a comment
      - name: Comment
        uses: marstamm/comment-and-label-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
