on: 
  issues:
    types: [opened]


jobs:
  comment_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Comment
        uses: marstamm/comment-test-app@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}